# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Papier < Formula
  desc "Perfectly inconvenient text editor"
  homepage "https://github.com/cestef/papier"
  url "https://github.com/cestef/papier/archive/refs/tags/v0.2.37.tar.gz"
  sha256 "7924076c3285e9e3a42e575b42519cbc6a9a2a0c9f0e8bd21682977e41d225fe"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/papier/releases/download/v0.2.37/papier-0.2.37-darwin-amd64.tar.gz"
      sha256 "a9f71fbcaf77acd71b71c4e7b52c6b37b22cc3bd1a21a99e9961c996d3cb5ef7"
    end

    on_arm do
      url "https://github.com/cestef/papier/releases/download/v0.2.37/papier-0.2.37-darwin-arm64.tar.gz"
      sha256 "66f964587b9b33df499a6459fe54a1ca76a00aae27e0f7de02f6aa99f12f35a8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/papier/releases/download/v0.2.37/papier-0.2.37-linux-amd64.tar.gz"
      sha256 "85651b5c250f46f65d442d5e46c7e1cdc4db51514600f553ab6da1e38b86943f"
    end

    on_arm do
      url "https://github.com/cestef/papier/releases/download/v0.2.37/papier-0.2.37-linux-arm64.tar.gz"
      sha256 "2b88532cd86a1827967f75edcb38ac82fcd2aa26de08d37c5e10e7156db5ade2"
    end
  end

  def install
    bin.install "ppr"
  end
end
