# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Papier < Formula
  desc "Perfectly inconvenient text editor"
  homepage "https://github.com/cestef/papier"
  url "https://github.com/cestef/papier/archive/refs/tags/v0.2.39.tar.gz"
  version "0.2.39"
  sha256 "b401c2bcf2931efbe4745be09c586a0e4b1322e4087e9340e69da044caf2f47c"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/papier/releases/download/v0.2.39/papier-0.2.39-darwin-amd64.tar.gz"
      sha256 "d63a040618fe6de20da9b0ce83a96a7e3ad6cbda8f0ad88c34a03799910aea23"
    end

    on_arm do
      url "https://github.com/cestef/papier/releases/download/v0.2.39/papier-0.2.39-darwin-arm64.tar.gz"
      sha256 "c04573323ddf7019132e578208e6206ca8de934540a2ae7748e1ee5ff61c6ec8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/papier/releases/download/v0.2.39/papier-0.2.39-linux-amd64.tar.gz"
      sha256 "321eab7e828557b867820a627051e61cce5e7c13d29314741e4018f462e9be43"
    end

    on_arm do
      url "https://github.com/cestef/papier/releases/download/v0.2.39/papier-0.2.39-linux-arm64.tar.gz"
      sha256 "ceeb79d4f0e1b9f8b50bbabe9cedc77fdbebf3bc32bd985c17ae7b90b42f5ddc"
    end
  end

  def install
    bin.install "ppr"
  end
end
