# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rwalk < Formula
  desc "Blazingly fast web directory scanner written in rust"
  homepage "https://github.com/cestef/rwalk"
  url "https://github.com/cestef/rwalk/archive/refs/tags/v0.9.1.tar.gz"
  version "0.9.1"
  sha256 "ada53621edfa093ce8f80048ae2f2a574e6410e5b75e92d3d3d1f13af3e3af25"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.9.1/rwalk-0.9.1-darwin-amd64.tar.gz"
      sha256 "303bdd04cd1d1cf500407fa4ca8b17adf2bb06371f080caf9331e16b4bf6851f"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.9.1/rwalk-0.9.1-darwin-arm64.tar.gz"
      sha256 "4d753a4969404430f8412a28e42284c83d167014dd09648bbf4efe5c2d3ad75d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.9.1/rwalk-0.9.1-linux-amd64.tar.gz"
      sha256 "b88a72d7a67e950fec981b29567989b0634fc48b20e366684fe0931b027d7856"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.9.1/rwalk-0.9.1-linux-arm64.tar.gz"
      sha256 "4bdc40080f835b0d2a2c77a690bd0785e1307942070425f55175a56a1ad5fc95"
    end
  end

  def install
    bin.install "rwalk"
  end
end
