# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rwalk < Formula
  desc "Blazingly fast web directory scanner written in rust"
  homepage "https://github.com/cestef/rwalk"
  url "https://github.com/cestef/rwalk/archive/refs/tags/v0.8.4.tar.gz"
  version "0.8.4"
  sha256 "92ec42bf0689859ce38ee443d376282d074dfe3bf5b99673991300236f4191dd"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.4/rwalk-0.8.4-darwin-amd64.tar.gz"
      sha256 "29c842bb5b139fa8dff19deed248e2f63d5f0b18f33865a182a7fab6a4d69ae7"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.4/rwalk-0.8.4-darwin-arm64.tar.gz"
      sha256 "10bd4c6a96ba5fb046e3ba2484b75bb1ee4b6341a8adc90a8f36411d4f4b9df9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.4/rwalk-0.8.4-linux-amd64.tar.gz"
      sha256 "06f303b963acf8f7b33a40418140e8af086a779d47ace4580aa7ca5b2228080e"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.4/rwalk-0.8.4-linux-arm64.tar.gz"
      sha256 "225797b61e015b7622ebe45f70874cf45eb78af814a05cbf7bc966b59f59fc30"
    end
  end

  def install
    bin.install "rwalk"
  end
end
