# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rwalk < Formula
  desc "Blazing fast web directory scanner written in rust"
  homepage "https://github.com/cestef/rwalk"
  url "https://github.com/cestef/rwalk/archive/refs/tags/v0.5.6.tar.gz"
  sha256 "bdbca96cdeb22eff47d3d1685264cf0ab5c747aa8977b08b168584f9c74c3807"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.5.6/rwalk-0.5.6-darwin-amd64.tar.gz"
      sha256 "8aaec7210acb9634e6c94f6a8823e7fa06f365eecf201c5c27c9e84e68387ffa"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.5.6/rwalk-0.5.6-darwin-arm64.tar.gz"
      sha256 "3ce58610cdf645f0e0fbf88d8b52c8130758b91fde51a015ea94c7aef2bc8fc7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.5.6/rwalk-0.5.6-linux-amd64.tar.gz"
      sha256 "32ca605120c549ecf0dfac3b48ee9b3a5d33da84b534dac477c2cc0868ed5379"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.5.6/rwalk-0.5.6-linux-arm64.tar.gz"
      sha256 "1fc714c8a03f476e884bc864b1843063570e02e109429f5dfed47ac433d2aed8"
    end
  end

  def install
    bin.install "rwalk"
  end
end
