# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rwalk < Formula
  desc "Blazingly fast web directory scanner written in rust"
  homepage "https://github.com/cestef/rwalk"
  url "https://github.com/cestef/rwalk/archive/refs/tags/v0.8.7.tar.gz"
  version "0.8.7"
  sha256 "e70684fcbc7e383b9a8f422e9cec7f28aa63cab171dc3d7e3de3bac27774746e"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.7/rwalk-0.8.7-darwin-amd64.tar.gz"
      sha256 "91d4700e682004c46405292b2df2b5defd523d121ff488022fc03c6cc373109d"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.7/rwalk-0.8.7-darwin-arm64.tar.gz"
      sha256 "151359139fa99baf1c0b66c04329fe5e9ad936e3e9fdda2d09b9f92498b10e0f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.7/rwalk-0.8.7-linux-amd64.tar.gz"
      sha256 "33f43765e787626e82507c4e7a3dd2490057dccc0a5ec74532743c183a5b82c6"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.7/rwalk-0.8.7-linux-arm64.tar.gz"
      sha256 "4d71c6c2f1e0dbcd0208a4e2e3eecfddc466454657d162c2793557194f83836b"
    end
  end

  def install
    bin.install "rwalk"
  end
end
