# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Rwalk < Formula
  desc "Blazingly fast web directory scanner written in rust"
  homepage "https://github.com/cestef/rwalk"
  url "https://github.com/cestef/rwalk/archive/refs/tags/v0.8.3.tar.gz"
  version "0.8.3"
  sha256 "c4e39eb420772260e31c91befd0afa1e792ca42945179a8501a192c5a373cc02"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.3/rwalk-0.8.3-darwin-amd64.tar.gz"
      sha256 "a8e234c4a82401028dd8387e38a838a6097ed5bfd88fe09f2748a68167b2db28"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.3/rwalk-0.8.3-darwin-arm64.tar.gz"
      sha256 "f1db0060113463466fcf10a2b4c8eae719cb3d5961f3feceac7106f1e8245824"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.3/rwalk-0.8.3-linux-amd64.tar.gz"
      sha256 "c01f10fb0b81f15d83c1a964bb5ec733407033d226909715a07f3e55bfeb2477"
    end

    on_arm do
      url "https://github.com/cestef/rwalk/releases/download/v0.8.3/rwalk-0.8.3-linux-arm64.tar.gz"
      sha256 "c51a147d81ed49b543083b0bc6b3946795bdca0a86f2615e6fe068a29b7713f1"
    end
  end

  def install
    bin.install "rwalk"
  end
end
